FROM rust:1.87-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev pkg-config build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN rustup component add rustfmt clippy
RUN cargo update -p time


